version: v1

parameters:
  stack_name:
    description: The stack name you wish to deploy as its defined in stackery
  environment_name:
    description: The environment you wish to deploy to as its defined in stackery
  slack_channel:
    description: Slack channel (include preceding hashtag)
  confetti: 
    description: Shoots confetti over everything.  Makes a mess. 
    default: false

steps:
- name: create-website-bucket
  image: projectnebula/cloudformation-deployer
  spec:
    aws:
      accessKeyID:
        $type: Secret
        name: aws_access_key_id
      secretAccessKey:
        $type: Secret
        name: aws_access_key_secret
      region: us-west-2
    stackName: nebula-stackery-demo-website-bucket
    template: |
      AWSTemplateFormatVersion: 2010-09-09
      Description: Nebula stackery example bucket
      Resources:
        WebsiteBucket:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: PublicRead
            WebsiteConfiguration:
              IndexDocument: index.html
              ErrorDocument: error.html
          DeletionPolicy: Retain
        BucketPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
            PolicyDocument:
              Id: MyPolicy
              Version: 2012-10-17
              Statement:
                - Sid: PublicReadForGetBucketObjects
                  Effect: Allow
                  Principal: '*'
                  Action: 's3:GetObject'
                  Resource: !Join 
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref WebsiteBucket
                      - /*
            Bucket: !Ref WebsiteBucket
      Outputs:
        BucketName:
          Value: !Ref WebsiteBucket
          Description: The name of the bucket
        WebsiteURL:
          Value: !GetAtt 
            - WebsiteBucket
            - WebsiteURL
          Description: URL for website hosted on S3
    confetti:
      $type: Parameter
      name: confetti      

- name: stackery-deploy
  image: projectnebula/stackery-deploy
  spec:
    stackery: 
      key: 
        $type: Secret
        name: stackery_api_key
      secret:
        $type: Secret
        name: stackery_api_secret
    stackName: 
      $type: Parameter
      name: stack_name
    templatePath: example-workflows/stackery-workflow/template.yaml
    environmentName: 
      $type: Parameter
      name: environment_name
    aws:
      accessKeyID:
        $type: Secret
        name: aws_access_key_id
      secretAccessKey:
        $type: Secret
        name: aws_access_key_secret
      region: us-west-2
    git: 
      name: deploy
      branch: tasks/stackery
      repository: https://github.com/puppetlabs/nebula-workflow-examples.git
    confetti: 
      $type: Parameter
      name: confetti

- name: deploy-front-end
  image: projectnebula/s3-uploader
  dependsOn: 
    - stackery-deploy
    - create-website-bucket
  spec: 
    aws: 
      accessKeyID:
        $type: Secret
        name: aws_access_key_id
      secretAccessKey:
        $type: Secret
        name: aws_access_key_secret
      region: us-west-2
    bucket: 
      $type: Output
      name: BucketName
      taskName: create-website-bucket
    sourcePath: example-workflows/stackery-workflow/src/html
    git: 
      name: deploy
      branch: tasks/stackery
      repository: https://github.com/puppetlabs/nebula-workflow-examples.git
    confetti: 
      $type: Parameter
      name: confetti
      
- name: slack-notify
  dependsOn: deploy-front-end
  image: projectnebula/slack-notification
  spec:
    apitoken:
       $type: Secret
       name: slack_token
    channel:
       $type: Parameter
       name: slack_channel
    message:
       $type: Output
       name: WebsiteURL
       taskName: create-website-bucket
    confetti: 
      $type: Parameter
      name: confetti
